org.gradle.jvmargs=-Xmx1024m -Xss512k -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+UseSerialGC -Dfile.encoding=COMPAT
org.gradle.parallel=false
org.gradle.workers.max=1
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.nonTransitiveRClass=true
android.overridePathCheck=true
android.suppressUnsupportedCompileSdk=36
