name: fusionplay_android_flutter
description: FusionPlay Android receiver frontend.
homepage: https://github.com/rosienosiesie/FusionPlay-Android
repository: https://github.com/rosienosiesie/FusionPlay-Android
issue_tracker: https://github.com/rosienosiesie/FusionPlay-Android/issues
publish_to: none
version: 1.2.4+10204

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/DLNA.svg
    - assets/airplay-broadcast.svg
    - assets/auto-wake.svg
    - assets/device-speaker.svg
    - assets/device-tablet.svg
    - assets/device-television.svg
    - assets/device-vehicle.svg
    - assets/icon-pause.svg
    - assets/icon-play-arrow.svg
    - assets/icon-power-settings-new.svg
    - assets/icon-close.svg
    - assets/icon-settings.svg
    - assets/icon-skip-next.svg
    - assets/icon-skip-previous.svg
    - assets/miplay-logo.svg
    - assets/music-note-placeholder.svg
    - assets/关于应用.svg
    - assets/导出日志.svg
    - assets/自定义名称.svg
  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSansVF.ttf
